### ISSUE TITLE
Notebook doesn't output as expected

### ISSUE THREAD

**Issue by ogrotten** [DonJayamanne/typescript-notebook#47]
Did I miss a config step or stumble across an incompatibility of some sort?

<img width="494" alt="image" src="https://user-images.githubusercontent.com/8119012/149570819-69caa63a-138f-4a65-b28b-b3ad9372b747.png">

REPL and example notebooks behave the same.

I installed the extension and the MS Jupyter extension and followed the Getting Started.

**Comment by DonJayamanne** [comment]
Please could you provide the following info:
* Version of VS Code
* Version of the extension
* Output from the output panel named `TypeScript kernel`
* Output from your developer tools (go into the command `Toggle Developer Tools` and open the console window)

**Comment by Gargantuan5k** [comment]
Same issue, details:
VSCode version: 1.63.2
Extension version: v2.0.6
Output from `TypeScript Kernel` panel:

```
Starting node c:\Users\siddh\.vscode\extensions\donjayamanne.typescript-notebook-2.0.6\out\extension\server\index.js & listening on 56412 & websock on 56411
Server Exited, error: [Error: spawn node ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn node',
  path: 'node',
  spawnargs: [
    '--inspect=56412',
    'c:\\Users\\siddh\\.vscode\\extensions\\donjayamanne.typescript-notebook-2.0.6\\out\\extension\\server\\index.js',
    '--port=56411',
    '--config=C:\\\\Users\\\\siddh\\\\AppData\\\\Local\\\\Temp\\\\tmp-36152-PFHlLJIFP3I7-.json'
  ]
}
Server Exited, code = -4058
```

No output in Developer Tools Console

Tried rolling back to extension version 2.0.5 and 2.0.4, still facing the same issue

**Comment by Gargantuan5k** [comment]
I think the issue is not with the extension, I had accidentally corrupted my NodeJS installation on my machine; reinstalling NodeJS fixed the issue for me

**Comment by Stephane-Ag** [comment]
Having this same issue.

VS Code version 1.64.2
Extension v2.0.6
I have no "Typescript kernel" tab or anything
I see this in developer tools console:
```
ERR request cancelled: Error: request cancelled
	at /home/stephane/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:685154
	at /home/stephane/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:685448
	at Immediate.<anonymous> (/home/stephane/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:685811)
	at processImmediate (internal/timers.js:461:21)
```
