### ISSUE TITLE
Cannot run any cell.

### ISSUE THREAD

**Issue by thornhill6305** [DonJayamanne/typescript-notebook#92]
Extension Version: 2.0.6
VSCode Version: 1.90.0

I tried running sample notebooks and even a simple console.log("Hello"); but its stuck on pending.

I got this error in the typescript kernel panel:
```
TSError: ⨯ Unable to compile TypeScript:
error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'webworker.iterable', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asyncgenerator', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.object', 'es2019.string', 'es2019.symbol', 'es2020.bigint', 'es2020.promise', 'es2020.sharedmemory', 'es2020.string', 'es2020.symbol.wellknown', 'es2020.intl', 'es2021.promise', 'es2021.string', 'es2021.weakref', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint', 'esnext.string', 'esnext.promise', 'esnext.weakref'.
packages/config-typescript/base.json(10,5): error TS5023: Unknown compiler option 'allowImportingTsExtensions'.
packages/config-typescript/base.json(13,15): error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'esnext'.
packages/config-typescript/base.json(14,25): error TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic'.

    at createTSError (/Users/josmontes/.vscode/extensions/donjayamanne.typescript-notebook-2.0.6/resources/scripts/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/Users/josmontes/.vscode/extensions/donjayamanne.typescript-notebook-2.0.6/resources/scripts/node_modules/ts-node/src/index.ts:754:19)
    at create (/Users/josmontes/.vscode/extensions/donjayamanne.typescript-notebook-2.0.6/resources/scripts/node_modules/ts-node/src/index.ts:765:36)
    at Object.register (/Users/josmontes/.vscode/extensions/donjayamanne.typescript-notebook-2.0.6/resources/scripts/node_modules/ts-node/src/index.ts:514:15)
    at evalmachine.<anonymous>:1:126
    at Script.runInContext (node:vm:135:12)
    at Script.runInNewContext (node:vm:140:17)
    at Object.runInNewContext (node:vm:292:38)
    at t.register (/Users/josmontes/.vscode/extensions/donjayamanne.typescript-notebook-2.0.6/out/extension/server/index.js:2:143748)
    at t.initialize (/Users/josmontes/.vscode/extensions/donjayamanne.typescript-notebook-2.0.6/out/extension/server/index.js:2:113786) {
  diagnosticText: "error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'webworker.iterable', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asyncgenerator', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.object', 'es2019.string', 'es2019.symbol', 'es2020.bigint', 'es2020.promise', 'es2020.sharedmemory', 'es2020.string', 'es2020.symbol.wellknown', 'es2020.intl', 'es2021.promise', 'es2021.string', 'es2021.weakref', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint', 'esnext.string', 'esnext.promise', 'esnext.weakref'.\n" +
    "packages/config-typescript/base.json(10,5): error TS5023: Unknown compiler option 'allowImportingTsExtensions'.\n" +
    "packages/config-typescript/base.json(13,15): error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'esnext'.\n" +
    "packages/config-typescript/base.json(14,25): error TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic'.\n",
  diagnosticCodes: [ 6046, 5023, 6046, 6046 ]
}
Server Exited, code = 1
```

**Comment by t1m0thy-michael** [comment]
@josmontes had the same issue when trying to run in a project that used TS-node itself. Unchecking "Register TS-node" setting seems to have fixed the problem
